### ISSUE TITLE
Loading subpages directly does not work (email validation, track details)

### ISSUE THREAD

**Issue by groma84** [Friends-of-OpenBikeSensor/obsApp#7]
According to multiple users clicking on the link to validate the email does only show a "loading" screen:
> Hallo zusammen, ich hab gerade versucht mich auf der Webseite zu registrieren. Aber wenn ich den Verifizierungslink in der Mail anklicke kommt nur eine leere Seite mit "Loading". Der Login geht leider daher nicht mit der Meldung, dass die E-Mail Adresse nicht bestätigt wurde.

**Comment by opatut** [comment]
Hello there. I get the same issue with the `Loading...` screen when I navigate to some track details page, then press F5 to reload it.

I believe it has something to do with these mime type errors from the console:

![image](https://user-images.githubusercontent.com/235784/99780256-84125180-2b16-11eb-8686-d225f45a6425.png)

It looks like the media files are tried to be loaded relative to the current path (`/track/<slug>`), instead of the application root. A [`<base href>`](https://www.w3schools.com/Tags/att_base_href.asp) might help ;)

**Comment by uwewoessner** [comment]
Base href was the right pointer.
it is specified in package.json
I set it to "/" now.

**Comment by opatut** [comment]
Works like a charm! :)
